name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    #needs: build_job
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy to Azure Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SEA_04A78D703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" #".next/standalone/" # App source code path
          #api_location: "" # Api source code path - optional
          #output_location: "" # Built app content directory - optional
          output_location: ".next/standalone" # Built app content directory, relative to app_location - optional

          app_build_command: "npm run build  && cp -r public .next/standalone/public && rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache" #RNA
          #app_build_command: "npm run build && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache" #RNA
          #api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache' #RNA: reduce image size

          ###### End of Repository/Build Configurations ######
        env: # Add environment variables here
          is_static_export: true
  # build_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Build Job
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Build
  #       run: "npm run build  && cp -r public .next/standalone/public && rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache" #RNA
        #run: npm run build && cp -r .next/static ./.next/standalone/.next/static
  #     - name: List standalone folder
  #       run: ls -R ./.next/standalone/.next/static
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v3
  #       with: 
  #         name: static-site-standalone
  #         path: ./.next/standalone/
  # download_artifact_job:
  #   name: Download Artifact Job
  #   runs-on: ubuntu-latest
  #   needs: build_job
  #   steps:
  #     - name: Dowload artifact
  #       uses: actions/download-artifact@v3
  #       with: 
  #         name: static-site-standalone
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    #needs: download_artifact_job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SEA_04A78D703 }}
          action: "close"