name: Download artefact

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build && cp -r .next/static ./.next/standalone/.next/static
      - name: List standalone folder
        run: ls -R ./.next/standalone/.next/static
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: static-site-standalone
          path: ./.next/standalone/
  download_artifact_job:
    name: Download Artifact Job
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Dowload artifact
        uses: actions/download-artifact@v3
        with: 
          name: static-site-standalone
